name: CI Build for macOS (x86_64 and arm64)

on:
  push:  # Automatically triggered for pushes
  pull_request:  # Automatically triggered for pull requests
  workflow_dispatch:  # Manually triggered via the GitHub Actions UI

jobs:
  build:
    name: Build on macOS ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        arch: [arm64, x86_64]  # Support both architectures (Apple Silicon + Rosetta for x86_64)

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Rosetta 2 if running on Apple Silicon and building for x86_64
      - name: Install Rosetta 2 (if needed for x86_64)
        if: runner.os == 'macOS' && matrix.arch == 'x86_64'
        run: |
          softwareupdate --install-rosetta --agree-to-license || echo "Rosetta 2 already installed"

      - name: Set architecture for build
        run: |
          if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
            export ARCH_CMD="arch -x86_64"
          else
            export ARCH_CMD=""
          fi
          echo "ARCH_CMD=$ARCH_CMD" >> $GITHUB_ENV

      - name: Install Homebrew
        run: |
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"  # Apple Silicon Homebrew path
          else
            eval "$(/usr/local/bin/brew shellenv)"    # x86_64 Homebrew path (via Rosetta)
          fi

      - name: Install dependencies with Homebrew
        run: |
          brew install cmake pkg-config sdl12-compat sdl_gfx yaml-cpp ccache

      # Manually download and build SDL_image using autotools
      - name: Download and install SDL_image
        run: |
          curl -LO https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12.tar.gz
          tar -xzf SDL_image-1.2.12.tar.gz
          cd SDL_image-1.2.12
          ./configure --prefix=$(brew --prefix sdl12-compat)  # Ensure SDL is found and installed in the correct path
          make -j$(sysctl -n hw.ncpu)
          sudo make install  # Install system-wide

      # Manually download and build SDL_mixer using autotools
      - name: Download and install SDL_mixer
        run: |
          curl -LO https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz
          tar -xzf SDL_mixer-1.2.12.tar.gz
          cd SDL_mixer-1.2.12
          ./configure --prefix=$(brew --prefix sdl12-compat)  # Ensure SDL is found and installed in the correct path
          make -j$(sysctl -n hw.ncpu)
          sudo make install  # Install system-wide

      - name: Ensure pkg-config can find SDL dependencies
        run: |
          export PKG_CONFIG_PATH=$(brew --prefix sdl12-compat)/lib/pkgconfig:$PKG_CONFIG_PATH
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Generate project files with CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPKG_CONFIG_EXECUTABLE=$(brew --prefix pkg-config)/bin/pkg-config

      - name: Build the project
        run: |
          cmake --build build --parallel $(( $(sysctl -n hw.ncpu) - 1 ))

      # Fix SDL distribute, sign the app, and create a ZIP
      - name: Fix, sign, and package the app
        run: |
          sudo xattr -cr build/openxcom.app
          codesign --force --deep --sign - build/openxcom.app
          cd build
          zip -r openxcom.zip openxcom.app

      - name: Archive built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openxcom_${{ matrix.arch }}
          path: build/openxcom.zip

      - name: ccache stats
        run: ccache -s --max-size=390MB
